### ISSUE TITLE
Licensing 

### ISSUE THREAD

**Issue by benmkw** [hmeyer/tessellation#1]
I was looking into rust libraries that do triangulation in 3D and the current ecosystem seems to be fairly sparse. 

Thus your library stands out especially because dual contouring definitely seems to be an advanced technique.

Because much of the rust ecosystem is licensed under MIT/Apache2/MPL terms I would kindly ask if you were to consider licensing your work under such terms as well to make it easier for a wider range of people to reuse that code.

If you have further questions feel free to ask for clarification and if you consider this issue invalid feel free to close as it’s certainly your personal decision how you want to license your work. 

Thanks for your consideration :)

**Comment by hmeyer** [comment]
Thanks for your interest in this library.
I hope the updated licensing works for you.
Feel free to reach out, if you have questions about this library.
This library didn't get much love recently, but of course, contributions in form of PRs are very welcome.

**Comment by benmkw** [comment]
Thanks a lot, I wanted to implement dual contouring so I definitely want to check out the implementation soonish and if something stands out to me send PRs along, also mentioned it in the wgpu-rs matrix chat and there was interest regarding this lib but of course it’s still a bit early days for rust graphics.

**Comment by benmkw** [comment]
the license in Cargo.toml would need to be updated, it seems like this would be supported syntax: https://github.com/rust-lang-nursery/license-exprs/blob/master/Cargo.toml#L5
