### ISSUE TITLE
add more geometry generation?

### ISSUE THREAD

**Issue by benmkw** [hmeyer/tessellation#3]
I was looking for something like this originally https://graphics.rwth-aachen.de:9000/Glow/glow-extras/-/tree/develop/geometry/glow-extras/geometry

Do you think it would make sense to port these files and incorporate them here?

**Comment by hmeyer** [comment]
I'm not sure I understand. What kind of geometry do you think about adding? And why?

**Comment by benmkw** [comment]
Method where you say I need a cube/ quad/ sphere/ mesh with some dimensions and it generates the triangles. But these would not require the conversion from implicit geometry and could thus be faster.

**Comment by hmeyer** [comment]
I see this library more as a tool to generate meshes from implicit geometries.
Generating regular meshes seems to be an orthogonal task (although super relevant and interesting to implement - thinking about all those platonic and archimedian and catalan solids...).
Once we have that explicit geometry library, one could build a wrapper around the two that integrates both.

**Comment by benmkw** [comment]
yeah only cause the name is tessellation I thought it might as well go here but see your point :D

**Comment by benmkw** [comment]
I'm also a bit too lazy to publish on crates.io so there is that part of the motivation as well :D

**Comment by hmeyer** [comment]
> I'm also a bit too lazy to publish on crates.io so there is that part of the motivation as well :D

You should give it a try. It's not too hard afterall.

**Comment by benmkw** [comment]
true but its also more about having people rely on me maintaining it while I'm not yet sure I want to make that commitment/ can provide that :) I'll ping if I have some work to share though 👍
