### ISSUE TITLE
adaptive dc/ remeshing

### ISSUE THREAD

**Issue by benmkw** [hmeyer/tessellation#5]
https://www.boristhebrave.com/2018/04/15/dual-contouring-tutorial/ (Extensions)

https://www.mattkeeter.com/projects/contours/

Would this be something thats currently supported/ reasonable to add? I came across it while looking for adaptive level of detail methods.

**Comment by hmeyer** [comment]
manifold dual contouring already does that.
See the relative_error parameter of ManifoldDualContouring::new().

**Comment by benmkw** [comment]
haha ok :) great work, thanks!
